### ISSUE TITLE
Lesson 14 Quiz

### ISSUE THREAD

**Issue by Drufer** [udacity/aipnd_issues_tracker#11]
Here is my code:
week_sales = int(mon_sales) + int(tues_sales) + int(wed_sales) + int(thurs_sales) + int(fri_sales)
print("This week's total sales: " + str(week_sales) + ".")

Here is my output:
This week's total sales: 529.

Here is the response:
That doesn't match my answer.  The total sales should be 529. If that is what you got, check that your string is formatted correctly.

If I remove the str function before week_sales in the code for the print line I get this error : "TypeError: Can't convert 'int' object to str implicitly"

Is this a bug or am I missing something?

**Comment by j-staab** [comment]
Hi @Drufer,
Thanks for raising this issue.  I believe the reason you get the error is that there isn't supposed to be a "." after 529

If you instead submit:
Here is my code:
week_sales = int(mon_sales) + int(tues_sales) + int(wed_sales) + int(thurs_sales) + int(fri_sales)
print("This week's total sales: " + str(week_sales))

Your code will pass the quiz.  Good Luck with the rest of the ND.
