### ISSUE TITLE
0:59: Output displays a tuple, not a list

### ISSUE THREAD

**Issue by mathresearch** [udacity/aipnd_issues_tracker#13]

**Comment by j-staab** [comment]
Hi @mathresearch ,
Thanks for raising  this issue.  If you could provide more details about where the "output displays a tuple, not a list".  Which lesson and section this happens within the video at 0:59.
Thanks for the clarification.
-Jennifer

**Comment by j-staab** [comment]
Hi @mathresearch , 
I just saw ticket # 14 - seems like this happens in Lesson2.3 #25 - if I am correct in this assumption let me know and I will close this ticket since ticket # 14 provides the Lesson location detail.
Thanks!
-Jennifer

**Comment by ronny-udacity** [comment]
duplicate of issue #14
