### ISSUE TITLE
Lesson 3 Quiz 20, Random Variables not accepted

### ISSUE THREAD

**Issue by robertavram** [udacity/aipnd_issues_tracker#16]
The test starts with
```
start_num = #some start number
end_num = #some end number that you stop when you hit
count_by = #some number to count by 
```
However the only way the test accepts the correct solution is if those variables are set to:
```
start_num = 5
end_num = 100
count_by = 2
```

**Comment by j-staab** [comment]
Hi @robertavram, 
Thanks for raising the issue.  I tried both question 1 and question 2 with the numbers:
start_num = 1
end_num = 10
count_by = 2 

And I test solution provided the correct value and didn't indicate any issue with my code.  It could be that someone already addressed this problem before I got to your ticket.  I've closed the ticket and I wanted to thank you for raising the issue.
Best Regards,
-Jennifer
