### ISSUE TITLE
Lesson 5.12 Handling Errors

### ISSUE THREAD

**Issue by elvis016** [udacity/aipnd_issues_tracker#17]
try:
    # some code
except ValueError, KeyboardInterrupt:
    # some code

These lines of codes does not work in python 3.6.5. It shall be changed to below lines of codes.

try:
    # some code
except (ValueError, KeyboardInterrupt):
    # some code

**Comment by ronny-udacity** [comment]
fixed the code block with a parenthesized tuple.
