### ISSUE TITLE
Lesson 2.5.23 - Module Import Syntax Error

### ISSUE THREAD

**Issue by gaufisher** [udacity/aipnd_issues_tracker#19]
Text description for allowing access to all objects of a model says:
```
from module_name
```

It should say:
```
import module_name
```

**Comment by gaufisher** [comment]
![Screen Shot 2018-04-08 at 12.44.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aca7191483540001218c148/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454fb6b7191a379ed0c2f55415d4bbc21254d58eeb9cb74fce36f34985619e880645b72c73f19fdee8618ee01ba208a1c84e5b5df4ac6fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e24f54a3133464ee7e336e0a.png)

**Comment by ronny-udacity** [comment]
fixed

<img width="748" alt="screen shot 2018-09-12 at 11 27 11" src="https://user-images.githubusercontent.com/42421205/45445363-dd50e180-b67e-11e8-9851-635ce2f9b22f.png">
