### ISSUE TITLE
3.7 - Boolean Expressions for Conditions

### ISSUE THREAD

**Issue by gonzaloorsi** [udacity/aipnd_issues_tracker#20]
Condition for BMI calculation is wrong.

weight = 55
height = 164 (in cm)

if 18.5 <= weight / height**2 < 25:
    print("BMI is considered 'normal'")

We should divide height by 100 cm to get it right :)

**Comment by j-staab** [comment]
Hi @gonzaloorsi, 
Thanks for raising this issue. We are working on the resolution now.
