### ISSUE TITLE
Lesson 2.2.17 List and Membership Operators

### ISSUE THREAD

**Issue by IrynaDemydova** [udacity/aipnd_issues_tracker#21]
I am not sure, but in the text description below the first video it may be should be written "list_of_random_things" instead of "lst_of_random_things"

**Comment by IrynaDemydova** [comment]
![bug.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46ea819d61cec1b99de6b546a749b2ce6b13262a7d52f2792884e57ce8432b515f5e1dad12510a42faeb9539e4e76224d50152a7842f4d7ed43c18a6b9871dbc03bf278d4c84b0bd8c5e8d.png)

**Comment by IrynaDemydova** [comment]
P.S. Sorry, correct image below.
![bug.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46ea819d61cec1b99de6b546a749b2ce6b13262a7d52f2792884e57ce8432b515f5e1dad12510a42faeb9539e4e76224d50152a7842f4d7ed43c16a6b9871dbc03bf288b4f84b7be8b5e8d.png)

**Comment by j-staab** [comment]
Hi @IrynaDemydova, 
Thanks for raising the issue, typos have now been fixed in the classroom.
