### ISSUE TITLE
Lesson 2.2.19 List Methods

### ISSUE THREAD

**Issue by IrynaDemydova** [udacity/aipnd_issues_tracker#22]
Double phrase "returns the smallest element in a list" in the description of min function.

**Comment by IrynaDemydova** [comment]
[Uploading 2.2.19 List Methods.png...]

**Comment by IrynaDemydova** [comment]
![2.2.19 List Methods.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46badac86dd3dae9a3e0ac57e470f580214923606b48e13b628ae92dbc56395b4d5a1fa5455e5e46f4a8df2fa1e73c708a5d58ec82640a72c02f0dbefad341eb5ee779c11ac7a4b6984ec2e23c20e5888c4c3d180c1181f65427ed.png)

**Comment by j-staab** [comment]
Hi @ IrynaDemydova, 
Thanks for finding and raising the issue with the typo.  It has been fixed in the classroom. Good Luck with the ND!
