### ISSUE TITLE
2.2.25 Dictionaries and Identity Operators

### ISSUE THREAD

**Issue by IrynaDemydova** [udacity/aipnd_issues_tracker#23]
A typo in lesson 2.2.25 Dictionaries and Identity Operators, subtitles in video, time 1.47, explanation was about dilithium which is not in dictionary, in subtitles is written "lithium".

**Comment by IrynaDemydova** [comment]
![2.2.25 Dictionaries and Identity Operators.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46badac86dd0d6e9abe0bc57ad52fe953b4f22606905ad2f30ace72db1567215164f31ec141a0e00a3bbca39baa47c32d5065ebe957f5566c36c18a8be831db750ec248c1e85b6bc8b1fc1bb3470e18d9d532c5c5446dda0006ceacc09da52e44ae94754a1113560e372307d469417733e26.png)

**Comment by ronny-udacity** [comment]
caption has been fixed
