### ISSUE TITLE
Lesson 2.2.29 Compound Data Structures, time: 0:30: output box does not correspond to code

### ISSUE THREAD

**Issue by IrynaDemydova** [udacity/aipnd_issues_tracker#24]
There should be "{'number': 2, 'weight': 4.002602, 'symbol': 'He'}

**Comment by IrynaDemydova** [comment]
![2.2.29 Compound Data Structures.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46badac86dd0dae9ace6b253ab48fe90696226672844903f6290e03caa507e124d435cec03070511afbd9b21b4b36d798e5a0aefd93c0970c16c11acb8834cbe52b3758d4997aaaec81d9ebc6278bec1da0d2c14171981f55c30a29a48ce5bf742e34c55a1017b.png)

**Comment by afshan-udacity** [comment]
Thanks for writing in about this. We're on it!

**Comment by ronny-udacity** [comment]
Python standard `dict` doesn't guarantee order, although it may change in the future.

https://docs.python.org/3.6/whatsnew/3.6.html#whatsnew36-compactdict
