### ISSUE TITLE
Lesson 2.4.2- Rest, Test Run returns no values.

### ISSUE THREAD

**Issue by Akuternin** [udacity/aipnd_issues_tracker#25]
When doing a quiz, the test run returns no values even if the code is copied directly from the answers. It worked fine in the past sections, but not here.

**Comment by afshan-udacity** [comment]
Thanks for reporting, we're on it!

**Comment by junolee** [comment]
Hm, I am not seeing this. By Lesson 2.4.2 are you referring to Lesson 2 - Data Types and Operators, Concept 3 - Quiz: Arithmetic Operators (concept 4 is solutions), question 2? It works for me, as you can see in the screenshot below.
![Screen Shot 2018-05-17 at 3.57.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac3fd80960997001251645d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f46b7191a37bf1172c4f5e585ecc3c4a4356bcbbd671f3e57862804e0ebcd8695975c43540fabc854ebf01ba21d84ed6bfe98c4ad2f42f67b6d5db1063474f4dcbed5727a19141c95df44de44451a6143164e0722431.png)

**Comment by junolee** [comment]
My mistake, are you referring to Lesson 2: Functions, the quiz on Defining Functions? There, "Test Run" will not print anything if you delete the print statements already provided to you in the programming quizzes. I'd edited the solutions to also include these print statements
