### ISSUE TITLE
Lesson 2.4.2 Defining functions

### ISSUE THREAD

**Issue by IrynaDemydova** [udacity/aipnd_issues_tracker#26]
In subtitles to video at 3:29 should be "value" instead of "volume"

**Comment by IrynaDemydova** [comment]
![2.4.2 Defining functions.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46badace6dd0c38d8aefb64dad53f7d42f5329703d0dac2563c7af6aaf50740b0a0c0abe4b4a5a15f5fd8f2aa4be6d268e5b5aedd16d5e27c76e18f9be840da313f871d51bdaebe5c01982fa3737e683854e3b1c061e89f65532a69d4ac04abb.png)

**Comment by ronny-udacity** [comment]
fixed
