### ISSUE TITLE
Lesson 2.4.14 Iterators and Generators

### ISSUE THREAD

**Issue by IrynaDemydova** [udacity/aipnd_issues_tracker#27]
Using a "for" loop instead of "four" loop, video 1:56

**Comment by IrynaDemydova** [comment]
![2.14.14.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46badacb77ccd2fdcda5fd53b652fa912a5265296b51a27224d3b27ae7437d55580e4eac41590c45aff0dc2da0a42062c80d55b98e30063e937f03a6aa8316b500bf22884886bebc8244c4e03537aa.png)

**Comment by ronny-udacity** [comment]
fixed
