### ISSUE TITLE
Lesson 2.6.3 - "irregardless" and other bad grammar

### ISSUE THREAD

**Issue by arccoza** [udacity/aipnd_issues_tracker#29]
This sentence:

> (irregardless of if the image is correctly classified)

in 2.6.3 Principle Objectives point 1.

_irregardless_ should be _regardless_.
The rest of the sentence is also basically gibberish.

**Comment by j-staab** [comment]
Hi @arccoza, 
Thanks for catching the bug and reporting it, it has been addressed in the lab. Good Luck with the rest of the ND.
