### ISSUE TITLE
Quiz: Assign and Modify Variables, bug ?

### ISSUE THREAD

**Issue by MikeHatchi** [udacity/aipnd_issues_tracker#3]
When I push 'Test Run', I've got numbers:
4500000.0
449000000.0
471450000.0
447877500.0
447627500.0

But when I submit the answer, it says:
'Your code printed something that isn't a number. Test Run your code to verify that it prints a number and nothing else!'

**Comment by MikeHatchi** [comment]
I get the point. That's not asked to show the result of each variable modification.

**Comment by letyrodridc** [comment]
Hi @MikeHatchi , just for confirmation, is it an error?

**Comment by MikeHatchi** [comment]
Hi Leticia, a bug you mean? no it's not. The quizz asked for one type of answer: only one number. And actually, I've too detailed my code and show each result at each step.

**Comment by letyrodridc** [comment]
Ok Thanks @MikeHatchi I will close the issue.

**Comment by j-staab** [comment]
Hi @MikeHatchi and @letyrodridc, 
Thanks for raising the ticket @MikeHatchi and thanks for checking the issue @letyrodridc. This ticket has been addressed and moved to closed.
