### ISSUE TITLE
Numpy - Part 3 - Lesson 6 - Typo in "Solving a Simplified Set of Equations"

### ISSUE THREAD

**Issue by letyrodridc** [udacity/aipnd_issues_tracker#30]
Solving a Simplified Set of Equations

It says:
"A linear combination of vector by scalars brings are to our next important topic: A system of Linear Equations."

The error is in "brings are"

Link: https://classroom.udacity.com/nanodegrees/nd089/parts/d3806bdb-600c-4dfb-ad5d-932a690db1af/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/7944df46-7a24-45ac-a27d-ac6620667108/concepts/852f9480-8058-4f61-bdc3-194408b72d92

**Comment by Ortalarel** [comment]
Thanks! issue is fixed.
