### ISSUE TITLE
2.5.26 Experimenting With An Interpreter

### ISSUE THREAD

**Issue by IrynaDemydova** [udacity/aipnd_issues_tracker#31]
Video 2:19, "shell" commands instead of "show" commands

**Comment by IrynaDemydova** [comment]
![2.5.26.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46badacf6dd0d5ebc3abaf51ab57f5973d047d317c05fa7f26d4b170be442f560e5f4eac400b5e17f5ac8f2db4aa2e32db025fb28c341521842f1bbeb98415be04b823824883bfbd8d48c8e82f68.png)

**Comment by Ortalarel** [comment]
Thank you for the feedback! We will fix the issue.

**Comment by ronny-udacity** [comment]
fixed
