### ISSUE TITLE
2.6.7 Command Line Arguments

### ISSUE THREAD

**Issue by IrynaDemydova** [udacity/aipnd_issues_tracker#32]
may be a typo, should be "three" instead of "four", please, see image attached in the comments

**Comment by IrynaDemydova** [comment]
![three.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46fc9c882687c1e5cdf9ad4cae58f3806b1c6526285df77d21d7bb29b9162c005f5f4ead12590c4da9ff8f39baa47e21d40854b088270a36d43703aeb9881eba03be208f4e8cb6ba834bc1fa70.png)

**Comment by IrynaDemydova** [comment]
![four.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46ee9b8f31c0cfeb9ffbb049a15ee4d6730472727050f57a22dde22eeb157a515f5f4fff400b5611faff9b37b4f46d2ede0356b49b381d66cc2f13adb2831abd05ba248a468db5bf8e4cd2a5.png)

**Comment by j-staab** [comment]
Hi @IrynaDemydova,
Thanks for catching the typo and doing such a nice job of showing where the issue is - it's been corrected.  I really appreciate the clarity and detail.  Good Luck with the ND!

**Comment by IrynaDemydova** [comment]
Hi @j-staab ,
you're welcome and thank you for kind wishes about ND! :) Thank you, too, for very detailed explanations on each step of Lab: Classifying Images, they are very helpful!  :)
