### ISSUE TITLE
2.5.17 Calling read Method with Integer

### ISSUE THREAD

**Issue by spiritechie** [udacity/aipnd_issues_tracker#33]
Missing quotation marks in example script encasing camelot.txt (2nd grey box from top)

**Comment by spiritechie** [comment]
![waffle_camelot.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5adbbd4d833fd30011ccf852/125516c66e82c728ace21e0d46ff959c258e86968ce8b246a852e4d665043761260ea62864c7b96aea432255595e4ca4100e5b43adf9892ba7e53d2383090debc3714d36976345f3e5db55ea43a82a994e8cbcbd8f4ec4eb3827e4828847371c1755.png)

**Comment by ronny-udacity** [comment]
fixed
