### ISSUE TITLE
Lesson 2.5.14 Practice: Handling Input Errors

### ISSUE THREAD

**Issue by Vimal-N** [udacity/aipnd_issues_tracker#40]
format syntax input of below code snippet in the main block needs to be updated to reflect correct number of cookies for each person

At present:
 if cookies_each:  # if cookies_each is not None
        message = "\nLet's party! We'll have {} people attending, they'll each get to eat {} cookies, and we'll have {} left over."
        print(message.format(people, cookies, leftovers))

to be changed to :
 if cookies_each:  # if cookies_each is not None
        message = "\nLet's party! We'll have {} people attending, they'll each get to eat {} cookies, and we'll have {} left over."
        print(message.format(people, cookies_each, leftovers))

**Comment by Vimal-N** [comment]
the print statement inside *Practice: Handling Input Errors* quiz needs to be corrected from `    if cookies_each:  # if cookies_each is not None
        message = "\nLet's party! We'll have {} people attending, they'll each get to eat {} cookies, and we'll have {} left over."
        print(message.format(people, *cookies*, leftovers))`

to 

`    if cookies_each:  # if cookies_each is not None
        message = "\nLet's party! We'll have {} people attending, they'll each get to eat {} cookies, and we'll have {} left over."
        print(message.format(people, *cookies_each*, leftovers))`

**Comment by ronny-udacity** [comment]
fixed
