### ISSUE TITLE
Lab Python 2.6.14. Calculating Results: Typo "fo" instead of "for"

### ISSUE THREAD

**Issue by IrynaDemydova** [udacity/aipnd_issues_tracker#41]

**Comment by IrynaDemydova** [comment]
![2.6.14.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46badacc6dd3d7ebc3abaf51ab57f5973d047d317c05fa7f26d4b170be442f560e5f4eac400b5e17f5ac8f2db4aa2e32db025fb28c341521842f1bbeb98b15be04b8258d4784bfbc8e4dc4ee2f68.png)

**Comment by Ortalarel** [comment]
Thank you, the issue has been fixed!
