### ISSUE TITLE
Typos in check_images.py

### ISSUE THREAD

**Issue by elizawolfe** [udacity/aipnd_issues_tracker#43]
From Intro to Python, Lesson 6: Classifying Images. See paragraph for: TODO: 2.-to-7

**Comment by elizawolfe** [comment]
https://github.com/udacity/AIPND/blob/master/intropylab-classifying-images/check_images.py

These are the typos that were immediately obvious:

Line 80: paramaters => parameters
Line 81: acheiving => achieving
Line 83: acheive => achieve
Line 90: arguements => arguments
Line 108: label => labels
Line 133: its' => its
Line 134: it's => its
Line 168: This file has one dog name per line => This file has one dog name per line.
Line 169: dog names are... => Dog names are...
________________________________

**Comment by ronny-udacity** [comment]
fixed
