### ISSUE TITLE
Lesson 5, 14 Handling Errors Quizz

### ISSUE THREAD

**Issue by JR-Git0** [udacity/aipnd_issues_tracker#45]
Hi there, just a miniscule error in the code:
the code in the python handling_errors.py
uses the cookies variable instead of the cookies_each variable

At the moment everybody of the party guests gets to eat all the cookies..

**Comment by JR-Git0** [comment]
the line in the code that should be changed is line 27 :)

**Comment by JR-Git0** [comment]
print(message.format(people, cookies_each, leftovers))
instead of
        print(message.format(people, cookies, leftovers))

**Comment by ronny-udacity** [comment]
duplicate issue #40
