### ISSUE TITLE
Lab Python 2.6.16. Printing Results: Typo

### ISSUE THREAD

**Issue by IrynaDemydova** [udacity/aipnd_issues_tracker#48]

**Comment by IrynaDemydova** [comment]
![2.6.16 Printing Results.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46badacc6dd3d5e9bffbb64db054fe93697422603c08b73832c9a138ad4d71040c1b5ca6535d0e4df8ff8829aee76a748d0d0bedd16c0c75953444aabe9003ad43eb7edf10d8eff6df0ed2e22f27e6818e4a3c18061089ff5d37a4994fda15.png)

Should be run_models_batch.sh

**Comment by j-staab** [comment]
Hi @IrynaDemydova, 
Thanks for raising the issues with the typo - it's been fixed.  
Best Regards,
-Jennifer
