### ISSUE TITLE
ExtraCurricular 2.5.2 Naive Bayes, Guess The Person Now - Typo

### ISSUE THREAD

**Issue by IrynaDemydova** [udacity/aipnd_issues_tracker#51]

**Comment by IrynaDemydova** [comment]
![2.5.2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46badacf6dd0c1e5cdf9ad4cae58f3806b1c6526285df77d21d7bb29b9162c005f5f4ead12590c4da9ff8f39baa47e21d40854b088270a36d43703adbf881eba03bc2483488cb6b5894dc7fa70.png)

Should be "three times" in the subtitles and "3 times" on the display.

**Comment by ronny-udacity** [comment]
fixed
