### ISSUE TITLE
3.1.5 Anaconda, Managing Packages - Quiz does not work correct

### ISSUE THREAD

**Issue by IrynaDemydova** [udacity/aipnd_issues_tracker#52]

**Comment by IrynaDemydova** [comment]
![3.1.5.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46bbdacb6dd7c1e5cdf9ad4cae58f3806b1c6526285df77d21d7bb29b9162c005f5f4ead12590c4da9ff8f39baa47e21d40854b088270a36d43703adbf881eba03bc25834784b5ba884fc2fa70.png)
It seems that Quiz does not work correct, it does not accept any answer, each answer is marked as "Try Again"

**Comment by ronny-udacity** [comment]
installing `pandas` will also include `numpy`
