### ISSUE TITLE
3.1.9 On Python versions at Udacity - Link does not work

### ISSUE THREAD

**Issue by IrynaDemydova** [udacity/aipnd_issues_tracker#53]

**Comment by IrynaDemydova** [comment]
![3.1.9.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46bbdacb6ddbc1e5cdf9ad4cae58f3806b1c6526285df77d21d7bb29b9162c005f5f4ead12590c4da9ff8f39baa47e21d40854b088270a36d43703adb0881eba03bc25834683b0bf824dc5fa70.png)
The indicated link does not work

**Comment by IrynaDemydova** [comment]
![3.1.9-page not found.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46bbdacb6ddbceb98eeeba03aa52e4d42f49327d2d46ef696097ec22ba416f43554d4bfd485c5945fef1d87da2b16d708a5c0abed03e5621c03b03b0aac04ee155e57dd205d0f4ae805ec1ef3724e289894a361702198aff5c35b2d4.png)
After clicking on indicated link - "Page not found"

**Comment by ronny-udacity** [comment]
fixed
