### ISSUE TITLE
Small typo in "More conditional quizzes" question 2

### ISSUE THREAD

**Issue by fabiocorneti** [udacity/aipnd_issues_tracker#6]
Replace "purschase" with "purchase" in the comment at the beginning of the quiz:

Url:

https://classroom.udacity.com/nanodegrees/nd089/parts/e939d638-6813-40a0-84e3-f38abc625f78/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/44a22f87-f7ce-4a9a-a1f5-86024edb0f29

**Comment by afshan-udacity** [comment]
Thank you it is fixed!
