### ISSUE TITLE
4.2.5 Vector Transpose instead of Vector Tranpose

### ISSUE THREAD

**Issue by IrynaDemydova** [udacity/aipnd_issues_tracker#60]

**Comment by IrynaDemydova** [comment]
![4.2.5.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac7013d3271010011729619/125516c66e82c728ace21e0d46bcdac86dd7c1e5cdf9ad4cae58f3806b1c6526285df77d21d7bb29b9162c005f5f4ead12590c4da9ff8f39baa47e21d40854b088270a36d43703adbf881eba02ba22834f86b7b48848c8fa70.png)

**Comment by ronny-udacity** [comment]
fixed
