### ISSUE TITLE
Quizz asks me to use docstrings before they are introduced

### ISSUE THREAD

**Issue by mikasjoman** [udacity/aipnd_issues_tracker#62]
In the Intro python course for python AI nano-degree. Lesson 4 defining functions, Vid 3. Quiz about writing the readable_timedelta() function, you ask me to write a docstring. But you have not introduced the concept... 

that happens in video 8 of that lesson. So you should remove that ... it just confuses the students who are new to be asked to do things that has not been explained at all.

**Comment by ronny-udacity** [comment]
fixed
