### ISSUE TITLE
Matplotlib and Seaborn Part 2

### ISSUE THREAD

**Issue by mishraishan31** [udacity/aipnd_issues_tracker#64]
In the solution file for jupyter notebook of Additional Plot Practice under matplotlib and Seaborn Part 2 under part 3 of the syllabus, the indexes are being hardcoded in the function 'additionalplot_solution_1()'  as below:

most_makes=fuel_econ['make'].value_counts().index[:18]

It will be better if we can do it automatically as below:

true_count = fuel_econ['make'].value_counts() > 80
indx = np.sum(true_count)
most_makes = fuel_econ['make'].value_counts().index[:indx]

**Comment by ronny-udacity** [comment]
Thanks for the suggestion.
