### ISSUE TITLE
2.Intro to python. Lesson 6 Lab Classifying Images:  14. Classifying Labels As Dogs

### ISSUE THREAD

**Issue by brianopedal** [udacity/aipnd_issues_tracker#65]
1.Fix: Sentence error: Should be: 'you will *be* reading ...'

2.Suggestion: Shorter sentences might be better for reading comprephension.

' With this function you will reading in the dognames.txt file from the workspace, creating a data structure(dictionary) to hold the valid dog names, compare the dog names to the classifier and pet image labels in the results dictionary(resutlts_dic), adjust the results dictionary to account for when the classifier and pet image labels are in agreement about an image being "a dog" or "not a dog".'

**Comment by ronny-udacity** [comment]
fixed
