### ISSUE TITLE
2.Intro to python. Lesson 6 Lab Classifying Images: 15. Calculating Results

### ISSUE THREAD

**Issue by brianopedal** [udacity/aipnd_issues_tracker#66]
Should be **inputting**

> With this function you will be **inputing** the results_dic (dictionary of lists from adjust_results4_isadog) to create a dictionary of results statistics (results_stats). This results statistics dictionary will just contain the statistic's name as the key and the value will simply be the statistic's numeric value.

**Comment by ronny-udacity** [comment]
fixed
