### ISSUE TITLE
Lesson 4.3 - Missing "." in test spec

### ISSUE THREAD

**Issue by fabiocorneti** [udacity/aipnd_issues_tracker#7]
The "readable_timedelta" quiz requires to add a "." at the end of the output, but the test fails if a dot is present.

**Comment by letyrodridc** [comment]
Verified that if the student adds the dot the solution **doesn't** fail.
It's according to the print in the lesson: "1 week(s) and 3 day(s)."
Thanks for reporting this. Maybe both solutions could be accepted to make students don't spend time on this issue.

**Comment by j-staab** [comment]
Hi @fabiocorneti, @olivererxleben and @letyrodridc,
Thanks for reporting this issue. As @letyrodridc verified - adding the "." in your answer will produce a successful test run;  whereas, leaving the "." off will produce a failed test run now.  Thanks!
