### ISSUE TITLE
Lesson 5 - Quiz: Variables and Assignment Operators - Changing Variables bug

### ISSUE THREAD

**Issue by mikejauregui** [udacity/aipnd_issues_tracker#9]

**Comment by mikejauregui** [comment]
Data:

Changing Variables
How does changing a variable affect another variable that was defined in terms of it? Let's look at an example.

Here’s the initial data about Mountain View's population and population density.

>>> mv_population = 74728
>>> mv_area = 11.995
>>> mv_density = mv_population/mv_area

Now we redefine the mv_population variable:

>>> mv_population = 75000

Issue observed: the variable mv_population is updated to a new value, so if you want to calculate the density or mv_density the correct result would be: 6252.6052 however the task asks us to return the int: >>> print(int(mv_density)) so the correct result wold be 6252 however this number is not part of the possible options to chose from and the only accepted option as a valid result is: 6229 which does not take into consideration the variable update in the last line of the task.

Expected: the number 6252 should be listed in as one of the options to choose from and should be the correct answer.

Please take a look at the attached image.
![Captura de pantalla 2018-04-04 a la(s) 10.10.57.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac4e885af16ca001870dff2/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b45cfe80284a2b726956f37a28c8b37cf2122f410e4f12fd591b4654fdf9972aa6a83977984019ad93320521957903a6aa874eb605bc218947d4e0b88d1dc0e83d24b48adc466b18030a95ed1f64fecd149501bc1ea35f5fb6113669e773347e4f911a7c2b6e6327adee92.png)

**Comment by mikejauregui** [comment]
Update: I went to the next section and it explains why my answer is not the correct one, so I'm closing this issue, on a side note, the task is not clear.

Thanks.

**Comment by mikejauregui** [comment]
.

**Comment by j-staab** [comment]
Hi @mikejauregui, 
Thanks for raising this issue regarding clarity of the lesson - we will review and see if the question can be more clearly worded.
